Index of 50th element
Consider an (8, 8) shape NumPy array. What is the index (x,y) of the 50th element?

Note: For counting the elements go row-wise. For example, in the array,

[[1, 5, 9],

 [3, 0, 2]]

the 5th element would be '0'.

In [1]:
import numpy as np

In [8]:
a = np.arange(64,dtype='int')
a=a.reshape(8,8)

In [10]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55],
       [56, 57, 58, 59, 60, 61, 62, 63]])

In [17]:
np.where(a==49)

(array([6], dtype=int64), array([1], dtype=int64))

In [16]:
np.unravel_index(49, (8,8))

(6, 1)

Which of the following would extract all the first 3 rows of the last 5 columns in a given numpy 2D array ‘a’?

In [ ]:
a[ :3 , -5: ]

So Many Functions
What will the output of np.arange(1,16,2).reshape(4, 2) be?

In [18]:
np.arange(1,16,2).reshape(4, 2)

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11],
       [13, 15]])

Given a single positive odd integer 'n' greater than 2, create a NumPy array of size (n x n) with all zeros and ones such that the ones make a shape like '+'. The lines of the plus must be present at the middle row and column.

In [20]:
n=5
x=np.zeros((n,n),dtype=int)
t=n//2
x[t,:]=1
x[:,t]=1
print(x)

[[0 0 1 0 0]
 [0 0 1 0 0]
 [1 1 1 1 1]
 [0 0 1 0 0]
 [0 0 1 0 0]]


Which of the following would extract all the rows of the first 3 columns in a given numpy 2D array ‘a’?

In [ ]:
a[:, :3]

In [23]:
np.eye(2, dtype = int).reshape(4, 1).T

array([[1, 0, 0, 1]])

In [24]:
import numpy as np
a = np.arange(10)
f = np.vectorize(lambda x: x+1)
f(a)


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [25]:
np.full((2,2), 1) == np.ones((2,2))

array([[ True,  True],
       [ True,  True]])

In [26]:
import numpy as np
a = np.array( [7, 10, 2, 4, 13, 16])
med = np.percentile(a, 50)
print(med)

8.5
