In [2]:
height = [12,13,14]

In [5]:
height*2.56


TypeError: can't multiply sequence by non-int of type 'float'

In [6]:
import numpy as np

In [8]:
np_height = np.array([12,13,14])

In [9]:
np_height*2.56

array([30.72, 33.28, 35.84])

Numpy method

In [10]:
np1 = np.array([1,2,3])
np2 = np.array([7,8,9])
print(np1+np2)

[ 8 10 12]


homogeneity of NumPy arrays

In [14]:
a=np.array( [1.0, 2, 3.5, 0.2, True] )
type(a[4])

numpy.float64

In [17]:
b=np.array((1,90))
b[0]=56
b

array([56, 90])